name: Hello Shaxzod Bratan

on:
  workflow_dispatch: # maunal trigger/
#   push:
#     branches:
#       - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST_DNS }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.MAC_PEM }}
          script: |
            cd api
            git pull 
            npm install 
            pm2 restart all
