name: route53 deployment

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SHAXA }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SHAXA }}
  AWS_HOST_ID: ${{ secrets.AWS_HOST_ID }}
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v4

      - name: File name gen
        run: echo "FILE_NAME=route53-$(date +%Y%m%d_%H%M%S).json" >> "$GITHUB_ENV"

      - name: Get list of route53 records
        run: aws route53 list-resource-record-sets --hosted-zone-id $AWS_HOST_ID  >> $FILE_NAME

      - name: Copy to s3 bucket
        run: |
          aws s3 cp $FILE_NAME s3://mybucet01 
          echo "Success"
