name: Hello Shaxzod

on: workflow_dispatch

jobs:
  hello:
    runs-on: ubuntu-latest # nav instance
    steps:
      - name: Git clone repo
        uses: actions/checkout@v4

      - name: Redeploy
        env:
          PRIVATE_KEY: ${{
            secrets.MAC_PEM }}
          HOST: ${{ vars.HOST_DNS }}
          USER: ${{ vars.USERNAME }}
        run: |
          chmod +x redeploy.sh
          sh redeploy.sh

      - name: Run Test cases
        run: |
          npm i newman
          newman run ./test/nodejs.postman_collection.json --env-var base_url=http://${{vars.HOST_DNS}}:2500 --reporters cli,emojitrain

      - name: Slack Notification
        uses: act10ns/slack@v1
        if: always()
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          message: "Deployed in EC2 !!!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
