name: Hello Shaxzod

on:
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest # nav instance
    steps:
      - name: Git clone repo
        uses: actions/checkout@v4

      - name: Redeploy
        env:
          PRIVATE_KEY: ${{ secrets.MAC_PEM }}
          HOST: ${{ vars.HOST_DNS }}
          USER: ${{ vars.USERNAME }}
        run: |
          chmod +x redeploy.sh
          sh redeploy.sh
      - name: Health
        run: |
          curl  'http://13.53.170.229:2500/health'
