name: Run postman test

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "*/5 * * * *"
jobs:
  hello:
    runs-on: ubuntu-latest # nav instance
    steps:
      - name: Git clone repo
        uses: actions/checkout@v4

      - name: Run Test cases
        env:
          HOST: ${{ vars.HOST_DNS }}
        run: |
          npm i newman
          newman run ./test/nodejs.postman_collection.json --env-var base_url=http://${{vars.HOST_DNS}}:2500 --reporters
      - name: Slack Notification
        uses: act10ns/slack@v1
        if: failure()
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          message: "Deployment faielid "
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
