name: On push main

on:
    workflow_dispatch:
#   push:
#     branches:
#       - main
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo 
        uses: actions/checkout@v4

      - name: Redeploy
     env: 
        PRIVATE_KEY: ${{  secrets.OKOK-PEM}}
     run: | 
      chmode +x redeplou.sh
      sh redeploy.sh
        