name: Run postman test

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest # nav instance
    steps:
      - name: Run Test cases
        run: |
          npm i newman
          newman run ./test/nodejs.postman_collection.json --env-var base_url=http://${{vars.HOST_DNS}}:2500
