name: Hello Shaxzod

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest # nav instance
    steps:
      - name: Git clone repo
        uses: actions/checkout@v4

      - name: Redeploy
        env:
          PRIVATE_KEY: ${{ secrets.MAC_PEM }}
          HOST: ${{ vars.HOST_DNS }}
          USER: ${{ vars.USERNAME }}
        run: |
          chmod +x redeploy.sh
          sh redeploy.sh

      - name: Run Test cases
        run: |
          npm i newman
          newman run ./test/nodejs.postman_collection.json --env-var base_url=${{vars.HOST_DNS}}

      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: "Job status"
          message: "Succses Deployed in EC2 !!!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
