name: Hello Shaxzod

on:
  workflow_dispatch: # maunal trigger/
#   push:
#     branches:
#       - main
jobs:
  hello:
    runs-on: ubuntu-latest # nav instance
    steps:
      - name: Git clone repo
        uses: actions/checkout@v4

      - name: Redeploy
        env:
          PRIVATE_KEY: ${{secrets.OKOK-PEM}}
        run: |
          chmod +x redeploy.sh
          sh redeploy.sh
